
# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Install node.js packages
      run: npm install
      
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  test-e2e:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js 14.x
       uses: actions/setup-node@v1
       with:
          node-version: 14.x
     - name: Cypress run
       uses: cypress-io/github-action@v2
       with:
          build: npm run build
          start: npm start


  sonar:
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: 79eeb93bc6634217bf1c16340f52579a7db53557
        with:
          args: 
            -Dsonar.organization=aymericbouchetcesi
            -Dsonar.projectKey=AymericBouchetCesi_CubeGrp2
            -Dsonar.sources=.
